src/Reference/QrPaymentReferenceGenerator.php
tests/Reference/QrPaymentReferenceGeneratorTest.php

Fixes #29 
This pr allows the `customerIdentificationNumber` in a reference number to have a flexible length between 4 and 11 characters. The total of `customerIdentificationNumber + referenceNumber` may still not exceed 26 characters.

Allow customer ids between 0 and 11 chars in QrPaymentReferenceGenerator

---

composer.json
src/Constraint/ValidCreditorReferenceValidator.php

Catching invalid characters is built right into this library.
See https://github.com/kmukku/php-iso11649/issues/1

Update kmukku/php-iso11649 to require v1.5 at least

---

src/PaymentPart/Output/HtmlOutput/Template/PaymentPartTemplate.php
src/PaymentPart/Output/HtmlOutput/Template/PrintableStylesTemplate.php
tests/TestData/HtmlOutput/qr-additional-information.html
tests/TestData/HtmlOutput/qr-additional-information.print.html
tests/TestData/HtmlOutput/qr-alternative-schemes.html
tests/TestData/HtmlOutput/qr-alternative-schemes.print.html
tests/TestData/HtmlOutput/qr-full-set.html
tests/TestData/HtmlOutput/qr-full-set.print.html
tests/TestData/HtmlOutput/qr-minimal-setup.html
tests/TestData/HtmlOutput/qr-minimal-setup.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount.print.html
tests/TestData/HtmlOutput/qr-payment-reference-non.html
tests/TestData/HtmlOutput/qr-payment-reference-non.print.html
tests/TestData/HtmlOutput/qr-payment-reference-scor.html
tests/TestData/HtmlOutput/qr-payment-reference-scor.print.html
tests/TestData/HtmlOutput/qr-ultimate-debtor.html
tests/TestData/HtmlOutput/qr-ultimate-debtor.print.html

* Improve css in HtmlOutput to define font for all child elements. This may be relevant if other css on the same page is present which may have a higher specificity otherwise.
* Adjust output of HtmlOutput in printable view to keep the same positioning of the payment part without the need for external adjustments in the integration.

Improve HtmlOutput css styles

---

src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php

Because the payment slip generation adjusts the cell height ratio, the document ratio used by the user must be retained, then reset after the generation.

TcPdfOutput : Fix cell height ratio

---

composer.json
composer.lock
example/example_scor.php
src/Reference/QrPaymentReferenceGenerator.php
src/Reference/RfCreditorReferenceGenerator.php
src/String/StringModifier.php
src/Validator/Exception/InvalidCreditorReferenceException.php
tests/Reference/RfCreditorReferenceGeneratorTest.php
tests/String/StringModifierTest.php

I found this missing and had to do some investigation before i found out how to work with it.
In my opinion, it makes sense to add a generator for this, working the same way as the `QrPaymentReferenceGenerator`. I think that's what you're looking for as a developer.
Looking at the QrPaymentReferenceGenerator:
Maybe I'm not understanding it, but as I see there a Validator in place, which is used in the `doGenerate()`-method. However, `getViolations()` seems inaccessible, as the instasnce is never exposed.
Of curse it's possible to get a new instance with `new`, but then it's not possible to set the properties.
Because of this I used a different approach for the creation and the facade in RfCreditorReferenceGenerator. But I'm open for inputs.

Added generator for ISO11649 Creditor Reference

---

src/PaymentPart/Output/FpdfOutput/FpdfOutput.php
src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php

Closes #86 
* Allows offset of positioning of the payment part in `FpdfOutput` and `TcPdfOutput` to be a `float` instead of an `int.`
* Fixes a bug with duplicated offsetting in `TcPdfOutput`

Use floats for offset in pdf outputs

---

src/PaymentPart/Translation/Translation.php
tests/PaymentPart/TranslationTest.php

According to the specifications document [docs/specs/ig-qr-bill-en-v2.1.pdf](https://github.com/sprain/php-swiss-qr-bill/blob/v3-wip/docs/specs/ig-qr-bill-en-v2.1.pdf) (as well as UBS who requested I make the change in my QR-Bills) the titles in French and Italian don't contain _de_ and _di_ respectively.

Update the 'Payment part' heading translations in French and Italian

---

.github/workflows/tests.yml
composer.json
composer.lock
src/DataGroup/Element/PaymentReference.php

Closes #156 
* Added support for Symfony 6 dependencies
* Dropped support for PHP 7.4 due to [this change](https://github.com/sprain/php-swiss-qr-bill/pull/157/files#diff-182360562153d1f40d925e43bcad454263d8818c36a0d97c7637785848d7c905R117).
* Dropped support for Symfony 3 dependencies
* Removed unneeded dev-dependencies

Add support for Symfony dependencies v6  by dropping PHP 7.4 support

---

src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php

TCPDF's AutoPageBreak is disabled, but not retained. This bugfix retains the original setting like it is already done for the CellHeightRatio.

Retain TCPDF's AutoPageBreak setting

---

src/DataGroup/Element/CombinedAddress.php
src/DataGroup/Element/StructuredAddress.php
tests/DataGroup/Element/CombinedAddressTest.php
tests/DataGroup/Element/StructuredAddressTest.php

Fixes #199 
The specification says:
> «For invoicing to countries outside Switzerland, including Lichtenstein[sic!], the country code should be printed on the payment section.»
This PR re-introduces the country code in Liechtenstein on payment parts which was removed in #188 based on a misunderstood bugfix.

Re-introduce output of country code for Liechtenstein

---

src/PaymentPart/Output/HtmlOutput/Template/PaymentPartTemplate.php
tests/TestData/HtmlOutput/qr-additional-information.svg.html
tests/TestData/HtmlOutput/qr-additional-information.svg.print.html
tests/TestData/HtmlOutput/qr-alternative-schemes.svg.html
tests/TestData/HtmlOutput/qr-alternative-schemes.svg.print.html
tests/TestData/HtmlOutput/qr-full-set.svg.html
tests/TestData/HtmlOutput/qr-full-set.svg.print.html
tests/TestData/HtmlOutput/qr-international-ultimate-debtor.svg.html
tests/TestData/HtmlOutput/qr-international-ultimate-debtor.svg.print.html
tests/TestData/HtmlOutput/qr-minimal-setup.svg.html
tests/TestData/HtmlOutput/qr-minimal-setup.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-with-mediumlong-creditor-and-unknown-debtor.svg.html
tests/TestData/HtmlOutput/qr-payment-information-with-mediumlong-creditor-and-unknown-debtor.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-and-long-addresses.svg.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-and-long-addresses.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-but-debtor.svg.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-but-debtor.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount.svg.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-zero-amount.svg.html
tests/TestData/HtmlOutput/qr-payment-information-zero-amount.svg.print.html
tests/TestData/HtmlOutput/qr-payment-reference-non.svg.html
tests/TestData/HtmlOutput/qr-payment-reference-non.svg.print.html
tests/TestData/HtmlOutput/qr-payment-reference-scor.svg.html
tests/TestData/HtmlOutput/qr-payment-reference-scor.svg.print.html
tests/TestData/HtmlOutput/qr-ultimate-debtor.svg.html
tests/TestData/HtmlOutput/qr-ultimate-debtor.svg.print.html

This pr adds additional `!important` and `color` statements to the styles of `HtmlOutput`. This makes sure the qr bill always looks according to specifications, regardless to other stylesheets that might be loaded in the document.

Make stylesheets of HtmlOutput stricter

---

composer.json
composer.lock
src/PaymentPart/Output/FpdfOutput/FpdfOutput.php
src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php
tests/PaymentPart/Output/FpdfOutput/FpdiOutputTest.php
tests/PaymentPart/Output/TcPdfOutput/FpdiOutputTest.php

With FPDI it is possible to manipulate existing PDF's like open and edit or merge them. The FPDI classes provide the same (and some more) functions as the base classes (Fpdf or tcPdf), so it was possible to just add the type
Their [homepage](https://www.setasign.com/)
Here's a little example how to print the bill on an existing PDF:
```php
$pdf = new Fpdi();
$pdf->AddPage();
$cnt = $pdf->setSourceFile($file);
$tplIdx = $pdf->importPage(1);
$pdf->useImportedPage($tplIdx);
$output = new FpdfOutput($qrBill, 'de', $pdf);
```
I think it would be a big advantage to include Fpdi.
Thank you for your time and work so far

Added support for Fpdi

---

.github/workflows/tests.yml
composer.json
composer.lock
src/PaymentPart/Output/FpdfOutput/FpdfOutput.php
src/PaymentPart/Output/FpdfOutput/UnsupportedEnvironmentException.php
tests/PaymentPart/Output/FpdfOutput/FpdfOutputTest.php
tests/PaymentPart/Output/FpdfOutput/FpdiOutputTest.php

This PR would add native support for Fpdf's [MemImage](http://www.fpdf.org/en/script/script45.php) script.
This would solve #192, but the tests depend on https://github.com/coreydoughty/Fpdf/pull/15 being accepted. Therefore this is marked as draft for now.

Added MemImage support for FpdfOutput

---

.github/workflows/tests.yml
composer.json
composer.lock

Looking good already :)
PHP 8.2 will be released on ~November 24, 2022~ December 8, 2022 ([source](https://externals.io/message/118991)).

Add support for PHP 8.2

---

src/PaymentPart/Output/FpdfOutput/FpdfOutput.php

Hi
since [utf8_decode has been deprecated ](https://www.php.net/manual/en/function.utf8-decode.php) on PHP8.2 it spits out notices.
I use FPDF also on other places and had the same there. According to the [FPDF FAQ](http://www.fpdf.org/en/FAQ.php) no.3 they recommend to use iconv() to convert 'UTF8' to 'windows-1252' which is expected.
The tests no produce errors, since I didn't manage to renew the .png-files in the QrCodes Test data.
Alltough the PDF's looked correct and scanning the QR-Code with my ebanking-app worked.
Thanks a lot for your work!
philipp

Remove deprecated UTF8_decode from FpdfOutput.php

---

src/PaymentPart/Output/FpdfOutput/FpdfOutput.php
tests/PaymentPart/Output/FpdfOutput/FpdfOutputTest.php

Acording to the [docs](https://www.php.net/manual/en/function.ini-get.php), `ini_get` should return "", "0" or "1" for boolean config
> Note: When querying boolean values A boolean ini value of off will be returned as an empty string or "0" while a boolean ini value of on will be returned as "1". The function can also return the literal string of INI value.
However, according to #214 there seem to be environments, that do not follow this. So it's probably best to test for truthy.

Test ini-parameter for truthy instead of string

---

src/PaymentPart/Output/AbstractOutput.php
src/PaymentPart/Output/FpdfOutput/FpdfOutput.php

Fixes #224 
Replace return type `self` with `static` in abstract method.
See https://www.php.net/manual/en/language.oop5.late-static-bindings.php for more information on why.

Fix method return type

---

composer.json
composer.lock
src/QrCode/QrCode.php

Add support for Endroid 5

---

src/PaymentPart/Output/HtmlOutput/Template/PaymentPartTemplate.php
tests/TestData/HtmlOutput/qr-additional-information.svg.html
tests/TestData/HtmlOutput/qr-additional-information.svg.print.html
tests/TestData/HtmlOutput/qr-alternative-schemes.svg.html
tests/TestData/HtmlOutput/qr-alternative-schemes.svg.print.html
tests/TestData/HtmlOutput/qr-full-set.svg.html
tests/TestData/HtmlOutput/qr-full-set.svg.print.html
tests/TestData/HtmlOutput/qr-international-ultimate-debtor.svg.html
tests/TestData/HtmlOutput/qr-international-ultimate-debtor.svg.print.html
tests/TestData/HtmlOutput/qr-minimal-setup.svg.html
tests/TestData/HtmlOutput/qr-minimal-setup.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-with-mediumlong-creditor-and-unknown-debtor.svg.html
tests/TestData/HtmlOutput/qr-payment-information-with-mediumlong-creditor-and-unknown-debtor.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-and-long-addresses.svg.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-and-long-addresses.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-but-debtor.svg.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount-but-debtor.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount.svg.html
tests/TestData/HtmlOutput/qr-payment-information-without-amount.svg.print.html
tests/TestData/HtmlOutput/qr-payment-information-zero-amount.svg.html
tests/TestData/HtmlOutput/qr-payment-information-zero-amount.svg.print.html
tests/TestData/HtmlOutput/qr-payment-reference-non.svg.html
tests/TestData/HtmlOutput/qr-payment-reference-non.svg.print.html
tests/TestData/HtmlOutput/qr-payment-reference-scor.svg.html
tests/TestData/HtmlOutput/qr-payment-reference-scor.svg.print.html
tests/TestData/HtmlOutput/qr-ultimate-debtor.svg.html
tests/TestData/HtmlOutput/qr-ultimate-debtor.svg.print.html

Improve stylesheets in HtmlOutput

---

src/DataGroup/Element/PaymentReference.php
src/QrBill.php
src/QrCode/QrCode.php
tests/QrBillTest.php
tests/QrCode/QrCodeTest.php
tests/TestQrBillCreatorTrait.php

Fixes #254
* Makes sure only supported characters are used within the qr code, removes others.
* Adds an option to provide custom replacements for unsupported characters. Example:
```php
$qrBill->setUnsupportedCharacterReplacements([
'«' => '"',
'»' => '"'
]);
```

Only keep supported characters within qr codes

---

composer.json
src/PaymentPart/Output/FpdfOutput/FpdfOutput.php
src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php

Fixes #245 
I'm not entirly shure what the method `toUtf8` did, but surely not convert to UTF-8. It converted away from UTF-8; ~~my best guess it that it's to replace characters that are not allowed in the payment slip?~~
~~`ISO-8859-1` should be correct here, as the specs require _Latin Character Set_. But maybe there was a specific reason that the previous characterset was chosen?~~
Also, `iconv` is not able to handle MultiByteCharacters (🦓🦓🦓), so maybe we can fix that by using `mb_*` instead. I explicitly added the Symfony `mb_*`-polyfill, as its an indirect dependency anyway, so it will not bloat the package.
~~This PR should be considered as breaking change.~~

Modernize encoding conversion for FPDF

---

.github/workflows/ci.yml
README.md
composer.json
example/FpdfOutput/fpdf-example.php
example/example.php
example/example_minimal.php
example/example_scor.php
example/example_zero_amount.php
rector.php
src/DataGroup/Element/AdditionalInformation.php
src/DataGroup/Element/AlternativeScheme.php
src/DataGroup/Element/CombinedAddress.php
src/DataGroup/Element/CreditorInformation.php
src/DataGroup/Element/Header.php
src/DataGroup/Element/PaymentAmountInformation.php
src/DataGroup/Element/PaymentReference.php
src/DataGroup/Element/StructuredAddress.php
src/PaymentPart/Output/AbstractOutput.php
src/PaymentPart/Output/DisplayOptions.php
src/PaymentPart/Output/FpdfOutput/FpdfOutput.php
src/PaymentPart/Output/FpdfOutput/FpdfTrait.php
src/PaymentPart/Output/HtmlOutput/HtmlOutput.php
src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php
src/QrBill.php
src/QrCode/QrCode.php
tests/PaymentPart/Output/FpdfOutput/FpdfOutputTest.php
tests/PaymentPart/Output/FpdfOutput/FpdiOutputTest.php
tests/PaymentPart/Output/TcPdfOutput/FpdiOutputTest.php
tests/PaymentPart/Output/TcPdfOutput/TcPdfOutputTest.php

* Drops support for PHP 8.0
* Adds support for PHP 8.4
* Adds modernizations available from PHP 8.1
* Adds policy on how long PHP versions and dependencies are supported

Drop support for PHP 8.0 | Add support for PHP 8.4

---

composer.json
example/FpdfOutput/fpdf-example.php
example/HtmlOutput/html-example.php
example/TcPdfOutput/tcpdf-example.php
rector.php
src/DataGroup/Element/Abstracts/Address.php
src/DataGroup/Element/CombinedAddress.php
src/DataGroup/Element/PaymentReference.php
src/DataGroup/Element/StructuredAddress.php
src/PaymentPart/Output/TcPdfOutput/TcPdfOutput.php
src/Reference/QrPaymentReferenceGenerator.php
tests/PaymentPart/Output/FpdfOutput/FpdfOutputTest.php
tests/PaymentPart/Output/FpdfOutput/FpdiOutputTest.php
tests/PaymentPart/Output/HtmlOutput/HtmlOutputTest.php
tests/PaymentPart/Output/TcPdfOutput/FpdiOutputTest.php
tests/PaymentPart/Output/TcPdfOutput/TcPdfOutputTest.php

Inspired by #269, I took a dive whether there's some more code to modernize. I realized, that you already added Rector in #265, but it seems like either the 8.1 preset was updated since then, or it was not fully applied?
This PR
- simplifies and improves the rector config
- `importNames` and `importShortClasses` config was kept
- `removeUnusedImports` was added
- `withPhpSets` uses the Composer config by default, so no explicit declaring of the set is required
- makes Output-examples more consistent and fixes, that Rector wants to remove the duplicate `Sprain\SwissQrBill as QrBill` import
- applies Rector for PHP81 set:
- explicit `(string)` casts to address the [deprecation of passing null to non-nullable parameters](https://www.php.net/manual/en/migration81.deprecated.php#migration81.dep …

Modernize: PHP81 with rector

---

src/Reference/QrPaymentReferenceGenerator.php
tests/Reference/QrPaymentReferenceGeneratorTest.php

Closes #275
Makes sure, the `QrPaymentReference` does not consist exclusively of zeros.

[Specs 2.3] Make sure the QrReference does not contain only zeros

---

.gitattributes

This reduces the amount of files downloaded/used when installing the package through composer without losing any functionality. The size is reduced from about 25.5MB to 0.25MB, saving lots of bandwidth and space. My whole vendor directory for a reasonably sized project is at 208MB, so getting rid of 25MB in just one package would be a good improvement.
The excluded files can be retrieved via the Github repository, in reality I do not think anybody will even notice they are gone. I also think it makes the package easier to use, as when you look at the installed package you only see the most relevant aspects (which are mainly src, examples, README).

Add .gitattributes to exclude non-essential files
